# Generated by Django 4.1.4 on 2022-12-25 12:39

import apps.api.services
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=apps.api.services.get_path_upload_cover_track, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg']), apps.api.services.validate_size_image]),
        ),
        migrations.AddField(
            model_name='track',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
